name: Comment Trigger

on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created, edited, deleted]

jobs:
 Comment:
   if: contains(github.event.comment.html_url, '/pull/')    # check if the comments come from pull request, exclude those from issue.
   runs-on: [ubuntu-latest]
   steps:
    - name: Build
      if: contains(github.event.comment.body, 'build')   # check the comment if it contains the keywords
      run: |
       echo BUILDING
    - name: Test
      if: contains(github.event.comment.body, 'full test')  # check the comment if it contains the keywords
      run: |
       echo test
