name: Publish Portfolio

on:
  push:
    branches: ['main']
    paths: ['package.json', 'public/**', 'src/components/**', 'src/App.css', 'src/App.js', 'src/index.js']

jobs:
 Build:
  runs-on: [ubuntu-latest]

  steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: ''
    
    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
  
    - name: Temporarily save build path
      uses: actions/upload-artifact@v2
      with:
        name: portfolio-build
        path: ./build
        retention-days: 3
 
 Publish:
  runs-on: [ubuntu-latest]
  needs: Build

  steps:
    - name: Retrieve saved build folder
      uses: actions/download-artifact@v2
      with:
        name: portfolio-build
        path: ./build
    
    - uses: keithweaver/aws-s3-github-action@v1.0.0
      name: Upload to S3
      with:
        command: sync
        source: ./build/
        destination: s3://emilsoleymani-portfolio-bucket/
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-1
        flags: --delete --recursive --cache-control max-age=31536000
    
    - uses: keithweaver/aws-s3-github-action@v1.0.0
      name: Remove caching of HTML and CSS files
      with:
        command: cp
        source: s3://emilsoleymani-portfolio-bucket/
        destination: s3://emilsoleymani-portfolio-bucket/
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: us-east-1
        flags: --recursive --exclude "*" --include "*.html" --include "*.css" --metadata-directive REPLACE --cache-control max-age:no-cache --content-type text/html
